version: '3.8'

  springboot-app:
    image: fa-check-image
    container_name: fa-check-container
    tty: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://curd-mysql-container:3306/middleware_system?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: koyembedu
      SPRING_DATASOURCE_PASSWORD: Admin@123
    ports:
      - "8081:8081"
    restart: always

volumes:
  mysql_data:
