package com.bp.middleware.util;

public class MiddlewareInvoice {

	
	String invoice="<!DOCTYPE html>\r\n"
			+ "<html lang=\"en\">\r\n"
			+ "<head>\r\n"
			+ "    <meta charset=\"UTF-8\">\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
			+ "    <title>Invoice</title>\r\n"
			+ "</head>\r\n"
			+ "<body>\r\n"
			+ "    \r\n"
			+ "\r\n"
			+ "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n"
			+ "    <title> Order confirmation </title>\r\n"
			+ "    <meta name=\"robots\" content=\"noindex,nofollow\" />\r\n"
			+ "    <meta name=\"viewport\" content=\"width=device-width; initial-scale=1.0;\" />\r\n"
			+ "    <style type=\"text/css\">\r\n"
			+ "      @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,700);\r\n"
			+ "      body { margin: 0; padding: 0; background: #c0c0c0; }\r\n"
			+ "      div, p, a, li, td { -webkit-text-size-adjust: none; }\r\n"
			+ "      .ReadMsgBody { width: 100%; background-color: #636363; }\r\n"
			+ "      .ExternalClass { width: 100%; background-color: #a09797; }\r\n"
			+ "      body { width: 100%; height: 100%; background-color: #eee5e5; margin: 0; padding: 0; -webkit-font-smoothing: antialiased; }\r\n"
			+ "      html { width: 100%; }\r\n"
			+ "      p { padding: 0 !important; margin-top: 0 !important; margin-right: 0 !important; margin-bottom: 0 !important; margin-left: 0 !important; }\r\n"
			+ "      .visibleMobile { display: none; }\r\n"
			+ "      .hiddenMobile { display: block; }\r\n"
			+ "    \r\n"
			+ "      @media only screen and (max-width: 600px) {\r\n"
			+ "      body { width: auto !important; }\r\n"
			+ "      table[class=fullTable] { width: 96% !important; clear: both; }\r\n"
			+ "      table[class=fullPadding] { width: 85% !important; clear: both; }\r\n"
			+ "      table[class=col] { width: 45% !important; }\r\n"
			+ "      .erase { display: none; }\r\n"
			+ "      }\r\n"
			+ "    \r\n"
			+ "      @media only screen and (max-width: 420px) {\r\n"
			+ "      table[class=fullTable] { width: 100% !important; clear: both; }\r\n"
			+ "      table[class=fullPadding] { width: 85% !important; clear: both; }\r\n"
			+ "      table[class=col] { width: 100% !important; clear: both; }\r\n"
			+ "      table[class=col] td { text-align: left !important; }\r\n"
			+ "      .erase { display: none; font-size: 0; max-height: 0; line-height: 0; padding: 0; }\r\n"
			+ "      .visibleMobile { display: block !important; }\r\n"
			+ "      .hiddenMobile { display: none !important; }\r\n"
			+ "      }\r\n"
			+ "    </style>\r\n"
			+ "    \r\n"
			+ "    \r\n"
			+ "    <!-- Header -->\r\n"
			+ "    <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\r\n"
			+ "      <tr>\r\n"
			+ "        <td height=\"20\"></td>\r\n"
			+ "      </tr>\r\n"
			+ "      <tr>\r\n"
			+ "        <td>\r\n"
			+ "          <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#ffffff\" style=\"border-radius: 10px 10px 0 0;\">\r\n"
			+ "            <tr class=\"hiddenMobile\">\r\n"
			+ "              <td height=\"40\"></td>\r\n"
			+ "            </tr>\r\n"
			+ "            <tr class=\"visibleMobile\">\r\n"
			+ "              <td height=\"30\"></td>\r\n"
			+ "            </tr>\r\n"
			+ "    \r\n"
			+ "            <tr>\r\n"
			+ "              <td>\r\n"
			+ "                <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullPadding\">\r\n"
			+ "                  <tbody>\r\n"
			+ "                    <tr>\r\n"
			+ "                      <td>\r\n"
			+ "                        <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"left\" class=\"col\">\r\n"
			+ "                          <tbody>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td align=\"left\"> <img src=\"./img/M.png.png\" width=\"80\" height=\"80\" alt=\"logo\" border=\"0\" /></td>\r\n"
			+ "                            </tr>\r\n"
			+ "                            <tr class=\"hiddenMobile\">\r\n"
			+ "                              <td height=\"40\"></td>\r\n"
			+ "                            </tr>\r\n"
			+ "                            <tr class=\"visibleMobile\">\r\n"
			+ "                              <td height=\"20\"></td>\r\n"
			+ "                            </tr>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td style=\"font-size: 15px; color: #5b5b5b; font-family: 'Open Sans', sans-serif; line-height: 18px; vertical-align: top; text-align: left;\">\r\n"
			+ "                                Hello, Merchant name.\r\n"
			+ "                                <br> Thank you for being a part of middleware family.\r\n"
			+ "                              </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                          </tbody>\r\n"
			+ "                        </table>\r\n"
			+ "                        <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"right\" class=\"col\">\r\n"
			+ "                          <tbody>\r\n"
			+ "                            <tr class=\"visibleMobile\">\r\n"
			+ "                              <td height=\"20\"></td>\r\n"
			+ "                            </tr>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td height=\"5\"></td>\r\n"
			+ "                            </tr>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td style=\"font-size: 26px; color: #ff9900; letter-spacing: -1px; font-family: 'Open Sans', sans-serif; line-height: 1; vertical-align: top; text-align: right;\">\r\n"
			+ "                                Middleware Invoice\r\n"
			+ "                              </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                            <tr>\r\n"
			+ "                            <tr class=\"hiddenMobile\">\r\n"
			+ "                              <td height=\"50\"></td>\r\n"
			+ "                            </tr>\r\n"
			+ "                            <tr class=\"visibleMobile\">\r\n"
			+ "                              <td height=\"20\"></td>\r\n"
			+ "                            </tr>\r\n"
			+ "                            <tr>\r\n"
			+ "                              <td style=\"font-size: 15px; color: #5b5b5b; font-family: 'Open Sans', sans-serif; line-height: 18px; vertical-align: top; text-align: right;\">\r\n"
			+ "                                <small>Invoice No: </small> #800000025<br />\r\n"
			+ "                                <small>Generated Date: </small> 9 Sep 2023<br />\r\n"
			+ "                              </td>\r\n"
			+ "                            </tr>\r\n"
			+ "                          </tbody>\r\n"
			+ "                        </table>\r\n"
			+ "                      </td>\r\n"
			+ "                    </tr>\r\n"
			+ "                  </tbody>\r\n"
			+ "                </table>\r\n"
			+ "              </td>\r\n"
			+ "            </tr>\r\n"
			+ "          </table>\r\n"
			+ "        </td>\r\n"
			+ "      </tr>\r\n"
			+ "    </table>\r\n"
			+ "    <!-- /Header -->\r\n"
			+ "    <!-- Order Details -->\r\n"
			+ "    <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\r\n"
			+ "      <tbody>\r\n"
			+ "        <tr>\r\n"
			+ "          <td>\r\n"
			+ "            <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#ffffff\">\r\n"
			+ "              <tbody>\r\n"
			+ "                <tr>\r\n"
			+ "                <tr class=\"hiddenMobile\">\r\n"
			+ "                  <td height=\"60\"></td>\r\n"
			+ "                </tr>\r\n"
			+ "                <tr class=\"visibleMobile\">\r\n"
			+ "                  <td height=\"40\"></td>\r\n"
			+ "                </tr>\r\n"
			+ "                <tr>\r\n"
			+ "                  <td>\r\n"
			+ "                    <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullPadding\">\r\n"
			+ "                      <tbody>\r\n"
			+ "                        <tr>\r\n"
			+ "                          <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 10px 7px 0;\" width=\"52%\" align=\"left\">\r\n"
			+ "                            From Date\r\n"
			+ "                          </th>\r\n"
			+ "                          <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 0 7px;\" align=\"left\">\r\n"
			+ "                            To Date\r\n"
			+ "                          </th>\r\n"
			+ "                          <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 0 7px;\" align=\"center\">\r\n"
			+ "                            Due Date\r\n"
			+ "                          </th>\r\n"
			+ "                          <th style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #1e2b33; font-weight: normal; line-height: 1; vertical-align: top; padding: 0 0 7px;\" align=\"right\">\r\n"
			+ "                            Total Hit\r\n"
			+ "                          </th>\r\n"
			+ "                        \r\n"
			+ "\r\n"
			+ "                        </tr>\r\n"
			+ "                        <tr>\r\n"
			+ "                          <td height=\"1\" style=\"background: #bebebe;\" colspan=\"4\"></td>\r\n"
			+ "                        </tr>\r\n"
			+ "                        <tr>\r\n"
			+ "                          <td height=\"10\" colspan=\"4\"></td>\r\n"
			+ "                        </tr>\r\n"
			+ "                        <tr>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #070707;  line-height: 18px;  vertical-align: top; padding:10px 0;\" class=\"article\">\r\n"
			+ "                            01.01.2023\r\n"
			+ "                          </td>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\">31.01.2023</td>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\" align=\"center\">05.02.2023</td>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #1e2b33;  line-height: 18px;  vertical-align: top; padding:10px 0;\" align=\"right\">78</td>\r\n"
			+ "                        </tr>\r\n"
			+ "                        <tr>\r\n"
			+ "                          <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\r\n"
			+ "                        </tr>\r\n"
			+ "                        <!-- <tr>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #ff9900;  line-height: 18px;  vertical-align: top; padding:10px 0;\" class=\"article\">Beats RemoteTalk Cable</td>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\"><small>MHDV2G/A</small></td>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e;  line-height: 18px;  vertical-align: top; padding:10px 0;\" align=\"center\">1</td>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #1e2b33;  line-height: 18px;  vertical-align: top; padding:10px 0;\" align=\"right\">$29.95</td>\r\n"
			+ "                        </tr> -->\r\n"
			+ "                        <tr>\r\n"
			+ "                          <td height=\"1\" colspan=\"4\" style=\"border-bottom:1px solid #e4e4e4\"></td>\r\n"
			+ "                        </tr>\r\n"
			+ "                      </tbody>\r\n"
			+ "                    </table>\r\n"
			+ "                  </td>\r\n"
			+ "                </tr>\r\n"
			+ "                <tr>\r\n"
			+ "                  <td height=\"20\"></td>\r\n"
			+ "                </tr>\r\n"
			+ "              </tbody>\r\n"
			+ "            </table>\r\n"
			+ "          </td>\r\n"
			+ "        </tr>\r\n"
			+ "      </tbody>\r\n"
			+ "    </table>\r\n"
			+ "    <!-- /Order Details -->\r\n"
			+ "    <!-- Total -->\r\n"
			+ "    <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\r\n"
			+ "      <tbody>\r\n"
			+ "        <tr>\r\n"
			+ "          <td>\r\n"
			+ "            <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#ffffff\">\r\n"
			+ "              <tbody>\r\n"
			+ "                <tr>\r\n"
			+ "                  <td>\r\n"
			+ "    \r\n"
			+ "                    <!-- Table Total -->\r\n"
			+ "                    <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullPadding\">\r\n"
			+ "                      <tbody>\r\n"
			+ "                        <tr>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; \">\r\n"
			+ "                            Subtotal\r\n"
			+ "                          </td>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; white-space:nowrap;\" width=\"80\">\r\n"
			+ "                            788.00\r\n"
			+ "                          </td>\r\n"
			+ "                        </tr>\r\n"
			+ "                        <!-- <tr>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; \">\r\n"
			+ "                            Shipping &amp; Handling\r\n"
			+ "                          </td>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #646a6e; line-height: 22px; vertical-align: top; text-align:right; \">\r\n"
			+ "                            $15.00\r\n"
			+ "                          </td>\r\n"
			+ "                        </tr> -->\r\n"
			+ "                        <tr>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #000; line-height: 22px; vertical-align: top; text-align:right; \">\r\n"
			+ "                            <strong>Grand Total (Incl.Tax)</strong>\r\n"
			+ "                          </td>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #000; line-height: 22px; vertical-align: top; text-align:right; \">\r\n"
			+ "                            <strong>807.00</strong>\r\n"
			+ "                          </td>\r\n"
			+ "                        </tr>\r\n"
			+ "                        <!-- <tr>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #b0b0b0; line-height: 22px; vertical-align: top; text-align:right; \"><small>TAX</small></td>\r\n"
			+ "                          <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #b0b0b0; line-height: 22px; vertical-align: top; text-align:right; \">\r\n"
			+ "                            <small>$72.40</small>\r\n"
			+ "                          </td>\r\n"
			+ "                        </tr> -->\r\n"
			+ "                      </tbody>\r\n"
			+ "                    </table>\r\n"
			+ "                    <!-- /Table Total -->\r\n"
			+ "    \r\n"
			+ "                  </td>\r\n"
			+ "                </tr>\r\n"
			+ "              </tbody>\r\n"
			+ "            </table>\r\n"
			+ "          </td>\r\n"
			+ "        </tr>\r\n"
			+ "      </tbody>\r\n"
			+ "    </table>\r\n"
			+ "    <!-- /Total -->\r\n"
			+ "    <!-- Information -->\r\n"
			+ "    <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\r\n"
			+ "      <tbody>\r\n"
			+ "        <tr>\r\n"
			+ "          <td>\r\n"
			+ "            <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#ffffff\">\r\n"
			+ "              <tbody>\r\n"
			+ "                <tr>\r\n"
			+ "                <tr class=\"hiddenMobile\">\r\n"
			+ "                  <td height=\"60\"></td>\r\n"
			+ "                </tr>\r\n"
			+ "                <tr class=\"visibleMobile\">\r\n"
			+ "                  <td height=\"40\"></td>\r\n"
			+ "                </tr>\r\n"
			+ "                <tr>\r\n"
			+ "                  <td>\r\n"
			+ "                    <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullPadding\">\r\n"
			+ "                      <tbody>\r\n"
			+ "                        <tr>\r\n"
			+ "                          <td>\r\n"
			+ "                            <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"left\" class=\"col\">\r\n"
			+ "    \r\n"
			+ "                              <tbody>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td style=\"font-size: 11px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 1; vertical-align: top; \">\r\n"
			+ "                                    <strong>BILLING INFORMATION</strong>\r\n"
			+ "                                  </td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td width=\"100%\" height=\"10\"></td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 20px; vertical-align: top; \">\r\n"
			+ "                                    Philip Brooks<br> Public Wales, Somewhere<br> New York NY<br> 4468, United States<br> T: 202-555-0133\r\n"
			+ "                                  </td>\r\n"
			+ "                                </tr>\r\n"
			+ "                              </tbody>\r\n"
			+ "                            </table>\r\n"
			+ "    \r\n"
			+ "    \r\n"
			+ "                            <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"right\" class=\"col\">\r\n"
			+ "                              <tbody>\r\n"
			+ "                                <tr class=\"visibleMobile\">\r\n"
			+ "                                  <td height=\"20\"></td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td style=\"font-size: 11px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 1; vertical-align: top; \">\r\n"
			+ "                                    <strong>PAYMENT METHOD</strong>\r\n"
			+ "                                  </td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td width=\"100%\" height=\"10\"></td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 20px; vertical-align: top; \">\r\n"
			+ "                                    Credit Card<br> Credit Card Type: Visa<br> Worldpay Transaction ID: <a href=\"#\" style=\"color: #ff0000; text-decoration:underline;\">4185939336</a><br>\r\n"
			+ "                                    <a href=\"#\" style=\"color:#b0b0b0;\">Right of Withdrawal</a>\r\n"
			+ "                                  </td>\r\n"
			+ "                                </tr>\r\n"
			+ "                              </tbody>\r\n"
			+ "                            </table>\r\n"
			+ "                          </td>\r\n"
			+ "                        </tr>\r\n"
			+ "                      </tbody>\r\n"
			+ "                    </table>\r\n"
			+ "                  </td>\r\n"
			+ "                </tr>\r\n"
			+ "                <tr>\r\n"
			+ "                  <td>\r\n"
			+ "                    <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullPadding\">\r\n"
			+ "                      <tbody>\r\n"
			+ "                        <tr>\r\n"
			+ "                          <td>\r\n"
			+ "                            <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"left\" class=\"col\">\r\n"
			+ "                              <tbody>\r\n"
			+ "                                <tr class=\"hiddenMobile\">\r\n"
			+ "                                  <td height=\"35\"></td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr class=\"visibleMobile\">\r\n"
			+ "                                  <td height=\"20\"></td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td style=\"font-size: 11px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 1; vertical-align: top; \">\r\n"
			+ "                                    <strong>SHIPPING INFORMATION</strong>\r\n"
			+ "                                  </td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td width=\"100%\" height=\"10\"></td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 20px; vertical-align: top; \">\r\n"
			+ "                                    Sup Inc<br> Another Place, Somewhere<br> New York NY<br> 4468, United States<br> T: 202-555-0171\r\n"
			+ "                                  </td>\r\n"
			+ "                                </tr>\r\n"
			+ "                              </tbody>\r\n"
			+ "                            </table>\r\n"
			+ "    \r\n"
			+ "    \r\n"
			+ "                            <table width=\"220\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"right\" class=\"col\">\r\n"
			+ "                              <tbody>\r\n"
			+ "                                <tr class=\"hiddenMobile\">\r\n"
			+ "                                  <td height=\"35\"></td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr class=\"visibleMobile\">\r\n"
			+ "                                  <td height=\"20\"></td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td style=\"font-size: 11px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 1; vertical-align: top; \">\r\n"
			+ "                                    <strong>SHIPPING METHOD</strong>\r\n"
			+ "                                  </td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td width=\"100%\" height=\"10\"></td>\r\n"
			+ "                                </tr>\r\n"
			+ "                                <tr>\r\n"
			+ "                                  <td style=\"font-size: 12px; font-family: 'Open Sans', sans-serif; color: #5b5b5b; line-height: 20px; vertical-align: top; \">\r\n"
			+ "                                    UPS: U.S. Shipping Services\r\n"
			+ "                                  </td>\r\n"
			+ "                                </tr>\r\n"
			+ "                              </tbody>\r\n"
			+ "                            </table>\r\n"
			+ "                          </td>\r\n"
			+ "                        </tr>\r\n"
			+ "                      </tbody>\r\n"
			+ "                    </table>\r\n"
			+ "                  </td>\r\n"
			+ "                </tr>\r\n"
			+ "                <tr class=\"hiddenMobile\">\r\n"
			+ "                  <td height=\"60\"></td>\r\n"
			+ "                </tr>\r\n"
			+ "                <tr class=\"visibleMobile\">\r\n"
			+ "                  <td height=\"30\"></td>\r\n"
			+ "                </tr>\r\n"
			+ "              </tbody>\r\n"
			+ "            </table>\r\n"
			+ "          </td>\r\n"
			+ "        </tr>\r\n"
			+ "      </tbody>\r\n"
			+ "    </table>\r\n"
			+ "    <!-- /Information -->\r\n"
			+ "    <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#e1e1e1\">\r\n"
			+ "    \r\n"
			+ "      <tr>\r\n"
			+ "        <td>\r\n"
			+ "          <table width=\"600\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullTable\" bgcolor=\"#ffffff\" style=\"border-radius: 0 0 10px 10px;\">\r\n"
			+ "            <tr>\r\n"
			+ "              <td>\r\n"
			+ "                <table width=\"480\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\" class=\"fullPadding\">\r\n"
			+ "                  <tbody>\r\n"
			+ "                    <tr>\r\n"
			+ "                      <td style=\"font-size: 12px; color: #5b5b5b; font-family: 'Open Sans', sans-serif; line-height: 18px; vertical-align: top; text-align: left;\">\r\n"
			+ "                        Have a nice day.\r\n"
			+ "                      </td>\r\n"
			+ "                    </tr>\r\n"
			+ "                  </tbody>\r\n"
			+ "                </table>\r\n"
			+ "              </td>\r\n"
			+ "            </tr>\r\n"
			+ "            <tr class=\"spacer\">\r\n"
			+ "              <td height=\"50\"></td>\r\n"
			+ "            </tr>\r\n"
			+ "    \r\n"
			+ "          </table>\r\n"
			+ "        </td>\r\n"
			+ "      </tr>\r\n"
			+ "      <tr>\r\n"
			+ "        <td height=\"20\"></td>\r\n"
			+ "      </tr>\r\n"
			+ "    </table>\r\n"
			+ "\r\n"
			+ "</body>\r\n"
			+ "</html>";
	
	
	
	
	
	
}
